/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppLayoutRouteImport } from './routes/_appLayout'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppLayoutTodoEditorLayoutRouteImport } from './routes/_appLayout/_todoEditorLayout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppLayoutTodoEditorLayoutUpcomingRouteImport } from './routes/_appLayout/_todoEditorLayout/upcoming'
import { Route as AppLayoutTodoEditorLayoutTodayRouteImport } from './routes/_appLayout/_todoEditorLayout/today'
import { Route as AppLayoutTodoEditorLayoutProjectsProjectIdRouteImport } from './routes/_appLayout/_todoEditorLayout/projects/$projectId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppLayoutTodoEditorLayoutRoute =
  AppLayoutTodoEditorLayoutRouteImport.update({
    id: '/_todoEditorLayout',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutTodoEditorLayoutUpcomingRoute =
  AppLayoutTodoEditorLayoutUpcomingRouteImport.update({
    id: '/upcoming',
    path: '/upcoming',
    getParentRoute: () => AppLayoutTodoEditorLayoutRoute,
  } as any)
const AppLayoutTodoEditorLayoutTodayRoute =
  AppLayoutTodoEditorLayoutTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AppLayoutTodoEditorLayoutRoute,
  } as any)
const AppLayoutTodoEditorLayoutProjectsProjectIdRoute =
  AppLayoutTodoEditorLayoutProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppLayoutTodoEditorLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/today': typeof AppLayoutTodoEditorLayoutTodayRoute
  '/upcoming': typeof AppLayoutTodoEditorLayoutUpcomingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectId': typeof AppLayoutTodoEditorLayoutProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppLayoutIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/today': typeof AppLayoutTodoEditorLayoutTodayRoute
  '/upcoming': typeof AppLayoutTodoEditorLayoutUpcomingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectId': typeof AppLayoutTodoEditorLayoutProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_appLayout/_todoEditorLayout': typeof AppLayoutTodoEditorLayoutRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_appLayout/': typeof AppLayoutIndexRoute
  '/_appLayout/_todoEditorLayout/today': typeof AppLayoutTodoEditorLayoutTodayRoute
  '/_appLayout/_todoEditorLayout/upcoming': typeof AppLayoutTodoEditorLayoutUpcomingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_appLayout/_todoEditorLayout/projects/$projectId': typeof AppLayoutTodoEditorLayoutProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/today'
    | '/upcoming'
    | '/api/auth/$'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/today'
    | '/upcoming'
    | '/api/auth/$'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_appLayout'
    | '/_auth'
    | '/_appLayout/_todoEditorLayout'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_appLayout/'
    | '/_appLayout/_todoEditorLayout/today'
    | '/_appLayout/_todoEditorLayout/upcoming'
    | '/api/auth/$'
    | '/_appLayout/_todoEditorLayout/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_appLayout/_todoEditorLayout': {
      id: '/_appLayout/_todoEditorLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutTodoEditorLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/_todoEditorLayout/upcoming': {
      id: '/_appLayout/_todoEditorLayout/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof AppLayoutTodoEditorLayoutUpcomingRouteImport
      parentRoute: typeof AppLayoutTodoEditorLayoutRoute
    }
    '/_appLayout/_todoEditorLayout/today': {
      id: '/_appLayout/_todoEditorLayout/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppLayoutTodoEditorLayoutTodayRouteImport
      parentRoute: typeof AppLayoutTodoEditorLayoutRoute
    }
    '/_appLayout/_todoEditorLayout/projects/$projectId': {
      id: '/_appLayout/_todoEditorLayout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppLayoutTodoEditorLayoutProjectsProjectIdRouteImport
      parentRoute: typeof AppLayoutTodoEditorLayoutRoute
    }
  }
}

interface AppLayoutTodoEditorLayoutRouteChildren {
  AppLayoutTodoEditorLayoutTodayRoute: typeof AppLayoutTodoEditorLayoutTodayRoute
  AppLayoutTodoEditorLayoutUpcomingRoute: typeof AppLayoutTodoEditorLayoutUpcomingRoute
  AppLayoutTodoEditorLayoutProjectsProjectIdRoute: typeof AppLayoutTodoEditorLayoutProjectsProjectIdRoute
}

const AppLayoutTodoEditorLayoutRouteChildren: AppLayoutTodoEditorLayoutRouteChildren =
  {
    AppLayoutTodoEditorLayoutTodayRoute: AppLayoutTodoEditorLayoutTodayRoute,
    AppLayoutTodoEditorLayoutUpcomingRoute:
      AppLayoutTodoEditorLayoutUpcomingRoute,
    AppLayoutTodoEditorLayoutProjectsProjectIdRoute:
      AppLayoutTodoEditorLayoutProjectsProjectIdRoute,
  }

const AppLayoutTodoEditorLayoutRouteWithChildren =
  AppLayoutTodoEditorLayoutRoute._addFileChildren(
    AppLayoutTodoEditorLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppLayoutTodoEditorLayoutRoute: typeof AppLayoutTodoEditorLayoutRouteWithChildren
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutTodoEditorLayoutRoute: AppLayoutTodoEditorLayoutRouteWithChildren,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
